import type { Metadata } from 'next'
import { MUIConfigProvider } from '@/core/configs/mui'
import { CollapseProvider } from '@/core/context/CollapseContext/CollapseContext.provider'
import { getColorScheme } from '../core/configs/next/cookies/colorScheme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const colorMode = await getColorScheme()

  return (
    <html lang="en" data-mui-color-scheme={colorMode}>
      <body>
        <CollapseProvider>
          <MUIConfigProvider colorMode={colorMode}>
            {children}
          </MUIConfigProvider>
        </CollapseProvider>
      </body>
    </html>
  )
}
