import type { Metadata } from 'next'

import { MUIConfigProvider } from '@/core/configs/mui'
import { ColorModeProvider } from '@/core/context/ColorModeContext/ColorModeContext.provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ColorModeProvider>
          <MUIConfigProvider>{children}</MUIConfigProvider>
        </ColorModeProvider>
      </body>
    </html>
  )
}
